---

- name: create system users
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    createhome: true
  with_items: "{{ users }}"

- name: set authorized key taken from file
  authorized_key:
    user: "{{ ansible_ssh_user }}"
    state: present
    key: "{{ lookup('file', authorized_key_file) }}"
  when: ansible_ssh_user is defined

- name: set timezone
  timezone:
    name: "{{ system_timezone }}"
  when: ansible_os_family == "RedHat"

- name: install basic applications
  yum:
    name: "{{ default_packages }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: install NTP via yum/dnf
  yum:
    name: chrony
    state: present
  notify: start ntp
  when: ansible_os_family == "RedHat" and install_ntp

- name: install firewall
  package:
    name: "{{ firewall_package }}"
    state: present
  notify: start firewall
  when: install_firewall

- name: add epel repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  when: ansible_os_family == "RedHat" and add_epel_repo

- name: add epel GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: ansible_os_family == "RedHat" and add_epel_repo

- name: change ssh port
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart sshd

- name: allow ssh port for RedHat
  firewalld:
    port: "{{ ssh_port }}/tcp"
    permanent: yes
    state: enabled
  notify:
    - reload firewall
  when: ansible_os_family == "RedHat" and install_firewall

- name: allow ssh port for Debian/ubuntu
  ufw:
    rule: allow
    name: OpenSSH
  when: ansible_os_family == "Debian" and install_firewall

- name: change selinux ssh port
  seport:
    ports: "{{ ssh_port }}"
    proto: tcp
    setype: ssh_port_t
    state: present
  when: ansible_os_family == "RedHat" and ansible_selinux.status == "enabled"
