---

- name: restart sshd
  systemd:
    state: restarted
    name: sshd

- name: reload firewall
  systemd:
    state: reloaded
    name: "{{ firewall_package }}"

- name: start ntp
  systemd:
    state: started
    enabled: yes
    name: chronyd

- name: start firewall
  systemd:
    state: started
    enabled: yes
    name: "{{ firewall_package }}"
