---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: instaall ssh (for molecule testing)
      package:
        name: openssh-server
        state: present

  roles:
    - role: quaded.bootstrap
  vars:
    users:
      - username: user1
      - username: user2
    install_firewall: False
